export const IMAGENET_CLASSES = {
  0: 'Agaricus arvensis',
  1: 'Cantharellus cibarius',
  2: 'Hygrophoropsis aurantiaca',
  3: 'Hydnum repandum',
  4: 'Pleurotus ostreatus',
  5: 'Cantharellus pallens',
  6: 'Tylopilus felleus',
  7: 'Sarcomyxa serotina',
  8: 'Agaricus xanthodermus',
  9: 'Boletus edulis',
  10: 'Pleurocybella porrigens',
  11: 'Lycoperdon Perlatum',
  12: 'Agaricus campestris',
  13: 'Hydnum umbilicatum',
  14: 'Rubroboletus satanas',
  15: 'Polyporus squamosus',
  16: 'Sarcodon squamosus',
  17: 'Boletus reticulatus',
  18: 'Pleurotus pulmonarius'
};