export const IMAGENET_CLASSES = {
  0: 'Horse mushroom',
  1: 'Chanterelle',
  2: 'False chantarelle',
  3: 'Wood hedgehog',
  4: 'Oyster mushroom',
  5: 'Cantharellus pallens',
  6: 'Bitter bolete',
  7: 'Sarcomyxa serotina',
  8: 'Yellow stainer',
  9: 'Penny bun',
  10: 'Angel\'s wings',
  11: 'Common puffball',
  12: 'Field mushroom',
  13: 'Depressed hedgehog',
  14: 'Devil\'s bolete',
  15: 'Dryad\'s saddle',
  16: 'Sarcodon squamosus',
  17: 'Summer bolete',
  18: 'Pale oyster'
};